# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detailsessionsender_pb2 as detailsessionsender__pb2


class DetailSessionSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDetailSession = channel.unary_unary(
                '/greet.DetailSessionSender/GetDetailSession',
                request_serializer=detailsessionsender__pb2.DetailSessionSenderRequest.SerializeToString,
                response_deserializer=detailsessionsender__pb2.DetailSessionSenderReply.FromString,
                )


class DetailSessionSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDetailSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetailSessionSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDetailSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailSession,
                    request_deserializer=detailsessionsender__pb2.DetailSessionSenderRequest.FromString,
                    response_serializer=detailsessionsender__pb2.DetailSessionSenderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.DetailSessionSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetailSessionSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDetailSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.DetailSessionSender/GetDetailSession',
            detailsessionsender__pb2.DetailSessionSenderRequest.SerializeToString,
            detailsessionsender__pb2.DetailSessionSenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
