# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detailtestsender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65tailtestsender.proto\x12\x05greet\")\n\x17\x44\x65tailListSenderRequest\x12\x0e\n\x06TestID\x18\x01 \x01(\x05\"w\n\rQuestionReply\x12\x14\n\x0cQuestionText\x18\x01 \x01(\t\x12\x16\n\x0eQuestionTypeID\x18\x02 \x01(\x05\x12\x10\n\x08MaxScore\x18\x03 \x01(\x05\x12\x11\n\tPictureID\x18\x04 \x01(\x05\x12\x13\n\x0bPicturePath\x18\x05 \x01(\t\"e\n\x13\x42\x61nkOfQuestionReply\x12\x12\n\nPositionID\x18\x01 \x01(\x05\x12\x12\n\nQuestionID\x18\x02 \x01(\x05\x12&\n\x08Question\x18\x03 \x01(\x0b\x32\x14.greet.QuestionReply\"n\n\x15\x44\x65tailTestSenderReply\x12\x0e\n\x06TestID\x18\x01 \x01(\x05\x12\x10\n\x08TestName\x18\x02 \x01(\t\x12\x33\n\x0f\x42\x61nkOfQuestions\x18\x03 \x03(\x0b\x32\x1a.greet.BankOfQuestionReply2a\n\x10\x44\x65tailTestSender\x12M\n\rGetDetailTest\x12\x1e.greet.DetailListSenderRequest\x1a\x1c.greet.DetailTestSenderReplyB\x1a\xaa\x02\x17ProfTestium_TestServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detailtestsender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027ProfTestium_TestService'
  _globals['_DETAILLISTSENDERREQUEST']._serialized_start=33
  _globals['_DETAILLISTSENDERREQUEST']._serialized_end=74
  _globals['_QUESTIONREPLY']._serialized_start=76
  _globals['_QUESTIONREPLY']._serialized_end=195
  _globals['_BANKOFQUESTIONREPLY']._serialized_start=197
  _globals['_BANKOFQUESTIONREPLY']._serialized_end=298
  _globals['_DETAILTESTSENDERREPLY']._serialized_start=300
  _globals['_DETAILTESTSENDERREPLY']._serialized_end=410
  _globals['_DETAILTESTSENDER']._serialized_start=412
  _globals['_DETAILTESTSENDER']._serialized_end=509
# @@protoc_insertion_point(module_scope)
