# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detailtestslist_pb2 as detailtestslist__pb2


class DetailTestsListSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuestionsList = channel.unary_unary(
                '/greet.DetailTestsListSender/GetQuestionsList',
                request_serializer=detailtestslist__pb2.GetQuestionsListRequest.SerializeToString,
                response_deserializer=detailtestslist__pb2.GetQuestionsListReply.FromString,
                )
        self.GetOpenQuestionAnswer = channel.unary_unary(
                '/greet.DetailTestsListSender/GetOpenQuestionAnswer',
                request_serializer=detailtestslist__pb2.GetOpenQuestionAnswersOfUserRequest.SerializeToString,
                response_deserializer=detailtestslist__pb2.GetOpenQuestionAnswerReply.FromString,
                )
        self.GetCloseQuestionAnswer = channel.unary_unary(
                '/greet.DetailTestsListSender/GetCloseQuestionAnswer',
                request_serializer=detailtestslist__pb2.GetVariantsAnswareOfCloseTypeQuestion.SerializeToString,
                response_deserializer=detailtestslist__pb2.GetCloseVariantsQuestionAnswerReply.FromString,
                )
        self.GetUserAnswers = channel.unary_unary(
                '/greet.DetailTestsListSender/GetUserAnswers',
                request_serializer=detailtestslist__pb2.GetUserAnswersRequest.SerializeToString,
                response_deserializer=detailtestslist__pb2.GetUserAnswersReply.FromString,
                )


class DetailTestsListSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuestionsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpenQuestionAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloseQuestionAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAnswers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetailTestsListSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuestionsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestionsList,
                    request_deserializer=detailtestslist__pb2.GetQuestionsListRequest.FromString,
                    response_serializer=detailtestslist__pb2.GetQuestionsListReply.SerializeToString,
            ),
            'GetOpenQuestionAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpenQuestionAnswer,
                    request_deserializer=detailtestslist__pb2.GetOpenQuestionAnswersOfUserRequest.FromString,
                    response_serializer=detailtestslist__pb2.GetOpenQuestionAnswerReply.SerializeToString,
            ),
            'GetCloseQuestionAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloseQuestionAnswer,
                    request_deserializer=detailtestslist__pb2.GetVariantsAnswareOfCloseTypeQuestion.FromString,
                    response_serializer=detailtestslist__pb2.GetCloseVariantsQuestionAnswerReply.SerializeToString,
            ),
            'GetUserAnswers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAnswers,
                    request_deserializer=detailtestslist__pb2.GetUserAnswersRequest.FromString,
                    response_serializer=detailtestslist__pb2.GetUserAnswersReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.DetailTestsListSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetailTestsListSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuestionsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.DetailTestsListSender/GetQuestionsList',
            detailtestslist__pb2.GetQuestionsListRequest.SerializeToString,
            detailtestslist__pb2.GetQuestionsListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOpenQuestionAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.DetailTestsListSender/GetOpenQuestionAnswer',
            detailtestslist__pb2.GetOpenQuestionAnswersOfUserRequest.SerializeToString,
            detailtestslist__pb2.GetOpenQuestionAnswerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCloseQuestionAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.DetailTestsListSender/GetCloseQuestionAnswer',
            detailtestslist__pb2.GetVariantsAnswareOfCloseTypeQuestion.SerializeToString,
            detailtestslist__pb2.GetCloseVariantsQuestionAnswerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserAnswers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.DetailTestsListSender/GetUserAnswers',
            detailtestslist__pb2.GetUserAnswersRequest.SerializeToString,
            detailtestslist__pb2.GetUserAnswersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
