# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detailsessionsender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64\x65tailsessionsender.proto\x12\x05greet\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x1a\x44\x65tailSessionSenderRequest\x12\x11\n\tSessionID\x18\x01 \x01(\x05\":\n\x16\x44\x65tailTestsSenderReply\x12\x0e\n\x06TestID\x18\x01 \x01(\x05\x12\x10\n\x08TestName\x18\x02 \x01(\t\"\x8b\x02\n\x11\x44\x65tailSessionUser\x12\x11\n\tsessionID\x18\x01 \x01(\x05\x12\x36\n\x0fTestsenderReply\x18\x02 \x01(\x0b\x32\x1d.greet.DetailTestsSenderReply\x12/\n\x0bSessionDate\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\tDurations\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0cIsSuccessful\x18\x05 \x01(\x08\x12\x15\n\rFailureReason\x18\x06 \x01(\t\x12\r\n\x05Score\x18\x07 \x01(\x05\x12\x10\n\x08MaxScore\x18\x08 \x01(\x05\"E\n\x18\x44\x65tailSessionSenderReply\x12)\n\x07session\x18\x01 \x01(\x0b\x32\x18.greet.DetailSessionUser2m\n\x13\x44\x65tailSessionSender\x12V\n\x10GetDetailSession\x12!.greet.DetailSessionSenderRequest\x1a\x1f.greet.DetailSessionSenderReplyB\x1a\xaa\x02\x17ProfTestium_TestServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detailsessionsender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027ProfTestium_TestService'
  _globals['_DETAILSESSIONSENDERREQUEST']._serialized_start=101
  _globals['_DETAILSESSIONSENDERREQUEST']._serialized_end=148
  _globals['_DETAILTESTSSENDERREPLY']._serialized_start=150
  _globals['_DETAILTESTSSENDERREPLY']._serialized_end=208
  _globals['_DETAILSESSIONUSER']._serialized_start=211
  _globals['_DETAILSESSIONUSER']._serialized_end=478
  _globals['_DETAILSESSIONSENDERREPLY']._serialized_start=480
  _globals['_DETAILSESSIONSENDERREPLY']._serialized_end=549
  _globals['_DETAILSESSIONSENDER']._serialized_start=551
  _globals['_DETAILSESSIONSENDER']._serialized_end=660
# @@protoc_insertion_point(module_scope)
