# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sessionsender_pb2 as sessionsender__pb2


class SessionSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionList = channel.unary_unary(
                '/greet.SessionSender/GetSessionList',
                request_serializer=sessionsender__pb2.SessionSenderRequest.SerializeToString,
                response_deserializer=sessionsender__pb2.SessionSenderReply.FromString,
                )


class SessionSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSessionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSessionList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionList,
                    request_deserializer=sessionsender__pb2.SessionSenderRequest.FromString,
                    response_serializer=sessionsender__pb2.SessionSenderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.SessionSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSessionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.SessionSender/GetSessionList',
            sessionsender__pb2.SessionSenderRequest.SerializeToString,
            sessionsender__pb2.SessionSenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
