# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sessionsender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sessionsender.proto\x12\x05greet\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n\x14SessionSenderRequest\x12\x0e\n\x06UserID\x18\x01 \x01(\x05\"4\n\x10TestsSenderReply\x12\x0e\n\x06TestID\x18\x01 \x01(\x05\x12\x10\n\x08TestName\x18\x02 \x01(\t\"\x94\x02\n\x0bSessionUser\x12\x11\n\tsessionID\x18\x01 \x01(\x05\x12\x31\n\x10TestssenderReply\x18\x02 \x01(\x0b\x32\x17.greet.TestsSenderReply\x12/\n\x0bSessionDate\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\tDurations\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x14\n\x0cIsSuccessful\x18\x05 \x01(\x08\x12\x15\n\rFailureReason\x18\x06 \x01(\t\x12\x12\n\nSessionUrl\x18\x07 \x01(\t\x12\r\n\x05Score\x18\x08 \x01(\x05\x12\x10\n\x08MaxScore\x18\t \x01(\x05\":\n\x12SessionSenderReply\x12$\n\x08sessions\x18\x01 \x03(\x0b\x32\x12.greet.SessionUser2Y\n\rSessionSender\x12H\n\x0eGetSessionList\x12\x1b.greet.SessionSenderRequest\x1a\x19.greet.SessionSenderReplyB\x1a\xaa\x02\x17ProfTestium_TestServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sessionsender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027ProfTestium_TestService'
  _globals['_SESSIONSENDERREQUEST']._serialized_start=95
  _globals['_SESSIONSENDERREQUEST']._serialized_end=133
  _globals['_TESTSSENDERREPLY']._serialized_start=135
  _globals['_TESTSSENDERREPLY']._serialized_end=187
  _globals['_SESSIONUSER']._serialized_start=190
  _globals['_SESSIONUSER']._serialized_end=466
  _globals['_SESSIONSENDERREPLY']._serialized_start=468
  _globals['_SESSIONSENDERREPLY']._serialized_end=526
  _globals['_SESSIONSENDER']._serialized_start=528
  _globals['_SESSIONSENDER']._serialized_end=617
# @@protoc_insertion_point(module_scope)
