# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import testlistsender_pb2 as testlistsender__pb2


class TestsListSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTestsList = channel.unary_unary(
                '/greet.TestsListSender/GetTestsList',
                request_serializer=testlistsender__pb2.TestsListSenderRequest.SerializeToString,
                response_deserializer=testlistsender__pb2.TestsListSenderReply.FromString,
                )


class TestsListSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTestsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestsListSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTestsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestsList,
                    request_deserializer=testlistsender__pb2.TestsListSenderRequest.FromString,
                    response_serializer=testlistsender__pb2.TestsListSenderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.TestsListSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestsListSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTestsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.TestsListSender/GetTestsList',
            testlistsender__pb2.TestsListSenderRequest.SerializeToString,
            testlistsender__pb2.TestsListSenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
