# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testlistsender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14testlistsender.proto\x12\x05greet\"\x18\n\x16TestsListSenderRequest\"-\n\tTestReply\x12\x0e\n\x06TestID\x18\x01 \x01(\x05\x12\x10\n\x08TestName\x18\x02 \x01(\t\"7\n\x14TestsListSenderReply\x12\x1f\n\x05Tests\x18\x01 \x03(\x0b\x32\x10.greet.TestReply2]\n\x0fTestsListSender\x12J\n\x0cGetTestsList\x12\x1d.greet.TestsListSenderRequest\x1a\x1b.greet.TestsListSenderReplyB\x1a\xaa\x02\x17ProfTestium_TestServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testlistsender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\027ProfTestium_TestService'
  _globals['_TESTSLISTSENDERREQUEST']._serialized_start=31
  _globals['_TESTSLISTSENDERREQUEST']._serialized_end=55
  _globals['_TESTREPLY']._serialized_start=57
  _globals['_TESTREPLY']._serialized_end=102
  _globals['_TESTSLISTSENDERREPLY']._serialized_start=104
  _globals['_TESTSLISTSENDERREPLY']._serialized_end=159
  _globals['_TESTSLISTSENDER']._serialized_start=161
  _globals['_TESTSLISTSENDER']._serialized_end=254
# @@protoc_insertion_point(module_scope)
