# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: useranswerssender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17useranswerssender.proto\x12\x05greet\";\n\x15GetUserAnswersRequest\x12\x12\n\nQuestionID\x18\x01 \x01(\x05\x12\x0e\n\x06UserID\x18\x02 \x01(\x05\"K\n\x0e\x41nswerVariants\x12\x11\n\tVariantID\x18\x01 \x01(\x05\x12\x13\n\x0bVariantText\x18\x02 \x01(\t\x12\x11\n\tIsCorrect\x18\x03 \x01(\x08\"\xbf\x01\n\x11UserQuestionReply\x12\x12\n\nQuestionID\x18\x01 \x01(\x05\x12\x14\n\x0cQuestionText\x18\x02 \x01(\t\x12\x10\n\x08MaxScore\x18\x03 \x01(\x05\x12\x11\n\tPictureID\x18\x04 \x01(\x05\x12\x13\n\x0bPicturePath\x18\x05 \x01(\t\x12)\n\nAnswersVar\x18\x06 \x03(\x0b\x32\x15.greet.AnswerVariants\x12\x1b\n\x13UserAsnwerVariantID\x18\x07 \x01(\x05\"@\n\x12GetUserAnswerReply\x12*\n\x08Question\x18\x01 \x01(\x0b\x32\x18.greet.UserQuestionReply2^\n\x11UserAnswersSender\x12I\n\x0eGetUserAnswers\x12\x1c.greet.GetUserAnswersRequest\x1a\x19.greet.GetUserAnswerReplyB\x1a\xaa\x02\x17ProfTestium_TestServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'useranswerssender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\027ProfTestium_TestService'
  _globals['_GETUSERANSWERSREQUEST']._serialized_start=34
  _globals['_GETUSERANSWERSREQUEST']._serialized_end=93
  _globals['_ANSWERVARIANTS']._serialized_start=95
  _globals['_ANSWERVARIANTS']._serialized_end=170
  _globals['_USERQUESTIONREPLY']._serialized_start=173
  _globals['_USERQUESTIONREPLY']._serialized_end=364
  _globals['_GETUSERANSWERREPLY']._serialized_start=366
  _globals['_GETUSERANSWERREPLY']._serialized_end=430
  _globals['_USERANSWERSSENDER']._serialized_start=432
  _globals['_USERANSWERSSENDER']._serialized_end=526
# @@protoc_insertion_point(module_scope)
